# Generated by Django 4.2.5 on 2023-10-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('code', models.IntegerField(choices=[('+91', '+91'), ('+1', '+1')])),
                ('phone', models.BigIntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=6)),
                ('job_role', models.CharField(choices=[('developer', 'developer'), ('testing', 'testing'), ('devops', 'devops')], max_length=10)),
                ('experience', models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')])),
                ('address', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('country', models.CharField(choices=[('india', 'india'), ('caneda', 'caneda'), ('uk', 'uk'), ('us', 'us')], max_length=20)),
            ],
        ),
    ]
