# Generated by Django 4.2.5 on 2023-10-05 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='address',
            new_name='address_line_one',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='address_line_two',
            field=models.CharField(default=django.utils.timezone.now, max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
