# Generated by Django 4.2.5 on 2023-10-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0002_rename_address_jobseeker_address_line_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='country',
            field=models.CharField(choices=[('india', 'india'), ('us', 'us')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='job_role',
            field=models.CharField(choices=[('developer', 'developer'), ('testing', 'testing'), ('devops', 'devops'), ('operations', 'operations'), ('accounting', 'accounting')], max_length=10),
        ),
    ]
