# Generated by Django 4.2.5 on 2023-10-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0004_jobseeker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='code',
            field=models.IntegerField(choices=[('+91', '+91'), ('+1', '+1')], max_length=3),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='country',
            field=models.CharField(choices=[('india', 'india'), ('us', 'us')], max_length=5),
        ),
    ]
