# Generated by Django 4.2.5 on 2023-10-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0006_alter_jobseeker_code_alter_jobseeker_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='country',
            field=models.CharField(max_length=5),
        ),
    ]
