# Generated by Django 4.2.5 on 2023-10-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0008_alter_jobseeker_address_line_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='zip_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
