# Generated by Django 4.2.5 on 2023-10-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0009_alter_jobseeker_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='code',
            field=models.CharField(choices=[('+91', '+91'), ('+1', '+1')], default='+91', max_length=3),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='country',
            field=models.CharField(choices=[('', 'Choose Country'), ('India', 'India'), ('US', 'US')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.CharField(choices=[('', 'Choose Experience (In years)'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], max_length=2),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='job_role',
            field=models.CharField(choices=[('', 'Choose Job Role'), ('Developer', 'Developer'), ('Testing', 'Testing'), ('Devops', 'Devops'), ('Operations', 'Operations'), ('Accounting', 'Accounting')], max_length=10),
        ),
    ]
