# Generated by Django 4.2.5 on 2023-10-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0010_alter_jobseeker_code_alter_jobseeker_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='dob',
            field=models.DateField(max_length=25),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(max_length=25),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
