# Generated by Django 4.2.5 on 2023-10-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0011_alter_jobseeker_dob_alter_jobseeker_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
