# Generated by Django 4.2.5 on 2023-10-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0012_alter_jobseeker_dob_alter_jobseeker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6),
        ),
    ]
