# Generated by Django 4.2.5 on 2023-10-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0020_alter_jobseeker_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='address_line_one',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='country',
            field=models.CharField(blank=True, choices=[('', 'Choose Country'), ('India', 'India'), ('US', 'US')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
