# Generated by Django 4.2.5 on 2023-10-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('min', '0021_alter_jobseeker_address_line_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
    ]
