# Generated by Django 4.2.5 on 2023-10-24 12:15

from django.db import migrations, models
import min.models


class Migration(migrations.Migration):
    dependencies = [
        ("min", "0027_alter_jobseeker_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseeker",
            name="dob",
            field=models.DateField(validators=[min.models.Jobseeker.validate_date]),
        ),
        migrations.AlterField(
            model_name="jobseeker",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="jobseeker",
            name="first_name",
            field=models.CharField(
                max_length=25, validators=[min.models.Jobseeker.validate_first_name]
            ),
        ),
        migrations.AlterField(
            model_name="jobseeker",
            name="phone",
            field=models.CharField(
                max_length=10, validators=[min.models.Jobseeker.validate_phone]
            ),
        ),
    ]
